export default [
    'MESSAGE_SEND',
    'MESSAGE_EDIT',
    'MESSAGE_DELETE',
    'MESSAGE_REACTION_ADD',
    'MESSAGE_REACTION_REMOVE',
    'TYPING',
    'POLL_VOTE_ADD',
    'POLL_VOTE_REMOVE',
    'ERROR'
]